# Generated by Django 3.2.2 on 2022-04-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindata',
            name='age',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='maindata',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='maindata',
            name='is_fat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maindata',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='maindata',
            name='photo',
            field=models.ImageField(default=1, upload_to='pics'),
        ),
    ]
